keys:
  - &admin_bling_hannes age1jvt938vlqcskd5f0ud0q5fpnaf6pnjxhen56ectkhf04y9guev6sg7ezsh
  - &device_vm1_hannes age19mhz5c440x8avdn3rrac65vajxkv6h7vjg2zkqucze55x5248uaque5xq7
  - &device_dominik age1rhh2cddzk7q4zj5wncxpyvqk0g805p9zm7t5lxy7aefw5jglte0sd4rxhq
  - &device_basti_root age18nhucgr7rhqeg0wtelxlncmp8zqqejxpnzjcea83zexf5h6lufzqnjzp4r
  - &device_hannes_m1 age1mljxyz8dfamwpnjjt8w2atq77cpk9e3cpjryrrt6mfwk0ulmsausufencr
  - &device_hannes_m1_userspace age120pvmf6npprc4z7rhvr643dvkxp62ksrvmt6axyyk9cctagfwy8qsprdlj
  - &device_hannes_air_cursorbook age10yavrraclt2a5mdq53kz48q3p0jpyp9rra487yamkvq6xx6qpgts34y8ft
  - &device_hannes_m4 age1pjauw376wq2dwaxdzjraedh4m7tdr6z5hqlyhnrlf4yj3c38dyxsgkrlr0
  - &device_david_user age1kn8x9gl4lz89mzldkj0g7jck5rzzwkgksakqpd25xyt4ce06r5dsqcv7h5
  - &device_david_root age16xwwdr5765pmqr9v3ns7eenuy7uj65njvkw8cwsncu2dk0f4ypjqxxjpy0
creation_rules:
  - path_regex: secrets/hannes/*
    key_groups:
      - age:
          - *device_hannes_m1_userspace
          - *device_hannes_m1
          - *device_hannes_m4
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_bling_hannes
          - *device_hannes_air_cursorbook
          - *device_vm1_hannes
          - *device_dominik
          - *device_basti_root
          - *device_hannes_m1
          - *device_hannes_m1_userspace
          - *device_hannes_m4
          - *device_david_user
          - *device_david_root
  - path_regex: .*
    key_groups:
      - age:
          - *admin_bling_hannes
          - *device_hannes_air_cursorbook
          - *device_vm1_hannes
          - *device_dominik
          - *device_basti_root
          - *device_hannes_m1
          - *device_hannes_m1_userspace
          - *device_hannes_m4
          - *device_david_user
          - *device_david_root
